# Generated by Django 5.0.1 on 2024-02-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmzoneapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='genres',
            field=models.CharField(choices=[('Action', 'Action'), ('Drama', 'Drama'), ('Comedy', 'Comedy'), ('Romance', 'Romance'), ('Science Fiction', 'Science Fiction')], default='Action', max_length=20),
        ),
    ]
