# Generated by Django 5.0.1 on 2024-02-16 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmzoneapp', '0002_movies_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='year',
            new_name='release_date',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='name',
            new_name='title',
        ),
    ]
