# Generated by Django 5.0.1 on 2024-02-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmzoneapp', '0005_genre_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('title',), 'verbose_name': 'genre', 'verbose_name_plural': 'genres'},
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='image',
        ),
    ]
