# Generated by Django 5.0.1 on 2024-03-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmzoneapp', '0006_alter_genre_options_rename_name_genre_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='ytube_trailer',
            field=models.URLField(),
        ),
    ]
