# Generated by Django 5.0.1 on 2024-03-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmzoneapp', '0007_alter_genre_title_alter_movie_ytube_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
